const $=id=>document.getElementById(id);let input=null,current=null,pending=false,generation=0;
const ms=n=>Number(n).toFixed(3)+' ms';
async function api(path,data){const r=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}:{});const b=await r.json();if(!r.ok)throw new Error(b.error||'请求失败');return b;}
function table(id,headers,rows){const t=document.createElement('table'),h=document.createElement('tr');for(const label of headers){const cell=document.createElement('th');cell.textContent=label;h.append(cell);}t.append(h);for(const row of rows){const tr=document.createElement('tr');for(const value of row){const td=document.createElement('td');td.textContent=value;tr.append(td);}t.append(tr);}$(id).replaceChildren(t);}
function plot(id,values,range){const canvas=$(id),rect=canvas.getBoundingClientRect(),dpr=devicePixelRatio||1;canvas.width=rect.width*dpr;canvas.height=rect.height*dpr;const c=canvas.getContext('2d');c.scale(dpr,dpr);const W=rect.width,H=rect.height,L=49,R=20,T=16,B=30,w=W-L-R,h=H-T-B,last=Math.max(1,values.length-1),px=x=>L+x/last*w,py=y=>T+(range[1]-y)/(range[1]-range[0])*h;c.font='11px "Microsoft YaHei", sans-serif';c.fillStyle='#8290a0';c.strokeStyle='#e9eff3';c.lineWidth=1;for(let i=0;i<=4;i++){const y=range[0]+(range[1]-range[0])*i/4;c.beginPath();c.moveTo(L,py(y));c.lineTo(W-R,py(y));c.stroke();c.fillText(id==='wave'?Math.round(y):y.toFixed(2),3,py(y)+4);}if(!values.length){c.fillText('点击按钮获取本次板上结果',L+20,T+h/2);return;}for(let i=0;i<=4;i++){const x=Math.round(last*i/4);c.fillText(String(x),px(x)-8,H-9);}
if(id==='wave'){c.fillStyle='#ecf1f6';for(const p of input.packets){const a=Math.max(0,p.start+64),b=Math.min(last,p.end-1);if(b>a)c.fillRect(px(a),T,px(b)-px(a),h);}}
function region(k,found){if(k<0||k>last)return;c.save();c.strokeStyle=found?'#008f88':'#8394a6';c.setLineDash(found?[]:[5,5]);c.lineWidth=1.4;if(id==='wave')c.strokeRect(px(k),T,Math.max(1,px(Math.min(last,k+63))-px(k)),h);else{c.beginPath();c.moveTo(px(k),T);c.lineTo(px(k),T+h);c.stroke();}c.restore();}
if(id==='wave')for(const k of input.expected_positions)region(k,false);for(const t of current?.result.targets||[])region(t.position,true);
if(id==='scores'){c.save();c.strokeStyle='#d09435';c.setLineDash([6,4]);c.beginPath();c.moveTo(L,py(.7));c.lineTo(W-R,py(.7));c.stroke();c.restore();}
c.beginPath();c.strokeStyle=id==='wave'?'#42798b':'#00978d';c.lineWidth=id==='wave'?1:1.7;values.forEach((v,i)=>i?c.lineTo(px(i),py(v)):c.moveTo(px(i),py(v)));c.stroke();}
function redraw(){plot('wave',input?.samples||[],[-2048,2048]);plot('scores',current?current.statistics.map(([s,e])=>e?Math.abs(s)/Math.sqrt(64*e):0):[],[0,1]);}
function clear(){current=null;$('source').className='badge neutral';$('source').textContent='输入预览';$('decision').textContent='等待实板计算';$('location').textContent='位置从 0 开始，前导码固定为 64 点。';$('targetList').textContent='等待实板结果';$('quality').textContent='计算正确性与应用检出效果分别核对。';$('scoreNote').textContent='等待本次窗口结果。';$('evidence').replaceChildren();for(const id of ['sw','hw','speedup','host'])$(id).textContent='—';}
function inputNote(){const actual=input.packets.filter(p=>p.target&&p.complete_preamble).map(p=>p.snr_db_actual).filter(x=>x!==null);$('inputNote').textContent=`${input.samples.length} 点 · 完整前导码真值：${input.expected_positions.length?input.expected_positions.join('、'):'无'} · 限幅 ${input.clipped_samples} 点${actual.length?' · 各目标实际 SNR '+actual.map(x=>x.toFixed(1)).join(' / ')+' dB':''}`;}
async function preview(){const token=++generation;clear();input=null;$('run').disabled=true;try{const c=await api('/api/preview',{case_id:$('case').value});if(token!==generation||pending)return;input=c;inputNote();$('notice').className='notice';$('notice').textContent='输入已更新。点击按钮，在真实 Z100 上完成定位和逐窗口核验。';$('run').disabled=false;redraw();}catch(e){if(token!==generation)return;$('notice').className='notice error';$('notice').textContent=e.message;redraw();}}
function show(data){input=data;current=data;const r=data.result,truth=new Set(data.expected_positions),found=new Set(r.targets.map(t=>t.position));const hits=[...truth].filter(k=>found.has(k)).length,misses=truth.size-hits,extras=[...found].filter(k=>!truth.has(k)).length;$('source').textContent='本次实板计算 · 已核对';$('source').className='badge'+(misses||extras?' warn':'');$('decision').textContent=r.target_count?`找到 ${r.target_count} 个候选位置`:'未找到候选前导码';$('location').textContent=r.target_count?`起点 ${r.targets.map(t=>t.position).join('、')} · 扫描 ${r.windows} 个窗口`:`扫描 ${r.windows} 个窗口，未达到阈值。`;$('quality').textContent=`真值 ${truth.size} 个 · 精确命中 ${hits} 个 · 漏检 ${misses} 个 · 额外检测 ${extras} 个${misses||extras?'；本次呈现真实应用边界。':''}`;$('sw').textContent=ms(r.software_cycles/50000);$('hw').textContent=ms(r.hardware_total_cycles/50000);$('speedup').textContent=(r.software_cycles/r.hardware_total_cycles).toFixed(2)+'×';$('host').textContent=ms(r.host_ms);if(r.target_count)table('targetList',['排序','起点','正反相','相关系数'],r.targets.map((t,i)=>[i+1,t.position,t.score<0?'反相':'正相',t.correlation_abs.toFixed(4)]));else $('targetList').textContent='没有达到阈值的候选位置。';inputNote();$('scoreNote').textContent=`全部 ${r.windows} 个窗口已由板上回读核对。最大绝对相关系数 ${r.correlation_abs===null?'无有效能量':r.correlation_abs.toFixed(4)}。`;
const rows=[['板上程序',data.build_id],['输入编号',data.id],['来源','真实 Z100 · 逐窗及完整列表核对'],['核心计算',ms(r.core_cycles/50000)],['完成时间',new Date(data.timestamp).toLocaleString()],['结果记录',data.run_id]];for(const [key,value]of rows){const dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=key;dd.textContent=value;$('evidence').append(dt,dd);}redraw();}
$('case').addEventListener('change',preview);$('run').addEventListener('click',async()=>{if(pending||!input)return;pending=true;generation++;$('case').disabled=$('run').disabled=true;clear();redraw();$('notice').className='notice';$('notice').textContent='正在发送样本、定位前导码并回读全部窗口…';try{show(await api('/api/run',{case_id:$('case').value}));$('notice').textContent='板上计算完成，全部窗口与完整列表均与独立参考一致。应用检出效果另列。';}catch(e){$('source').className='badge warn';$('source').textContent='本次未通过';$('decision').textContent='实板计算未完成';$('notice').className='notice error';$('notice').textContent=e.message;}finally{pending=false;$('case').disabled=false;$('run').disabled=!input;}});
window.addEventListener('resize',redraw);
(async()=>{try{const cfg=await api('/api/config');$('device').textContent=`${cfg.port} · 50 MHz · ${cfg.build_id}`;for(const c of cfg.cases){const o=document.createElement('option');o.value=c.id;o.textContent=c.label;$('case').append(o);}await preview();const r=await api('/api/report');if(r.status==='PASS'){$('reportStatus').textContent=r.engineering_goals_met?'实板核验及预设工程目标通过':'实板计算已核验，应用目标有未满足项';$('reportSummary').textContent=`1704 段固定应用数据＋60 次性能重复；核心应用 ${r.core.hits}/${r.core.targets} 个前导码命中，非目标集 ${r.negative.false_alarm_frames}/1000 段出现误报。`;
table('coreTable',['报文数','最弱报文设定 SNR','数据块','命中 / 目标','额外检测'],r.core_groups.map(x=>[x.count,x.snr_db+' dB',x.frames,`${x.hits} / ${x.targets}`,x.extras]));table('groupTable',['分组','数据块','命中 / 目标','漏检','额外检测'],r.groups.map(x=>[r.group_labels[x.group],x.frames,x.targets?`${x.hits} / ${x.targets}`:'—',x.misses,x.extras]));for(const img of document.querySelectorAll('#reportPlots img'))img.src=img.dataset.src;$('reportPlots').hidden=false;$('downloads').hidden=false;}else $('reportStatus').textContent='正式实板报告尚未生成';}catch(e){$('notice').className='notice error';$('notice').textContent=e.message;}})();
